### ISSUE TITLE
2020年6月20日(土)20時からLT会

### ISSUE THREAD

**Issue by defaultcf** [defaultcf/lt#9]
https://i544c.me/lt/events/2020/06/20/lt-in-vr.html

[Hubs](https://hubs.mozilla.com/)を使ったLT会を開催します。発表テーマは定めていません。
- 最近勉強している内容の紹介
- 便利なツールの紹介
- 推しの布教
など、自由に発表してください。

発表を考えている人は、ここにその旨書いてください。発表内容が決まっていれば、簡単な概要を書いてくれると嬉しいです（例「SELinuxについて話します」）。

**Comment by ShiranuiNui** [comment]
アマチュア無線か労基法36条か雇用保険の紹介を法律に触れない範囲でやりたい(願望)(精神が死んでいるのでスライドが完成する確率は0.1%未満な模様)

**Comment by ShiranuiNui** [comment]
> アマチュア無線か労基法36条か雇用保険の紹介を法律に触れない範囲でやりたい(願望)(精神が死んでいるのでスライドが完成する確率は0.1%未満な模様)

無理そうでち……申しわけ無いでち

**Comment by i544c** [comment]
@ShiranuiNui 悲しい...また今度やる時に是非！
